### ISSUE TITLE
Down::Http via a proxy?

### ISSUE THREAD

**Issue by grantyoung** [janko/down#45]
I was wondering if there's any guidance around using the `Down::Http` variant with a proxy? You have some docs for `Down::NetHttp` but none for `http.rb`.

Thanks in advance!

**Comment by janko** [comment]
For `Down::Http` you can pass [proxy options](https://github.com/httprb/http/wiki/Proxy-Support) to the client object:

```rb
# initialization
Down::Http.new { |client| client.via("proxy-hostname.local", 8080) }
# ad-hoc
Down::Http.open("https://example.com") do |client|
  client.via("proxy-hostname.local", 8080)
end
```

`Down::NetHttp` is documented because the options differ a bit from how you would do it using open-uri & net/http directly. But http.rb configuration is more uniform, so `Down::Http` just exposes the `HTTP::Client` and then you can do with it whatever you would normally do with http.rb.

**Comment by grantyoung** [comment]
Ah many thanks for the quick reply @janko!
