### ISSUE TITLE
Download via NetHttp and Cookie header fails

### ISSUE THREAD

**Issue by openscript** [janko/down#57]
Thank you for your work on this gem.

I've a problem with downloading a file, where I need to set a cookie:

```
      dossier_file = Down::NetHttp.download(
        dossier_path,
        read_timeout: 300,
        headers: {
          'Cookie': "#{Settings.cookies.session_token}=#{@session_token}",
          'User-Agent': @user_agent
        }
      )
```

When I do exactly the same with `open` it works.

```
unrecognized option: Cookie
/usr/local/lib/ruby/3.0.0/open-uri.rb:111:in `block in check_options'
/usr/local/lib/ruby/3.0.0/open-uri.rb:108:in `each'
/usr/local/lib/ruby/3.0.0/open-uri.rb:108:in `check_options'
/usr/local/lib/ruby/3.0.0/open-uri.rb:132:in `open_uri'
/usr/local/lib/ruby/3.0.0/open-uri.rb:721:in `open'
/usr/local/bundle/gems/down-5.2.1/lib/down/net_http.rb:146:in `open_uri'
/usr/local/bundle/gems/down-5.2.1/lib/down/net_http.rb:93:in `download'
/usr/local/bundle/gems/down-5.2.1/lib/down/backend.rb:13:in `download'
```

**Comment by janko** [comment]
open-uri accepts only one set of keyword arguments; arguments with symbol keys are interpreted as one of the [supported options](https://github.com/ruby/ruby/blob/4aaa98e62663f1e6e999c8741fe5bd518d178e0c/lib/open-uri.rb#L93-L104), while arguments with string keys are interpreted as request headers.

In ruby, `'foo': "bar"` is the same as `foo: "bar"`. So, in your case open-uri is interpreting the header names as open-uri options. You can fix this by correctly using string for header names.

This doesn't happen for `Down::NetHttp#open` because that method doesn't use open-uri, it uses net/http directly, to which header values are forwarded more explicitly.

**Comment by openscript** [comment]
Whoa!! Thank you for the super quick precise response. I now also see it in the README, which I read before, but I just naively thought if it works for `open` it also should work for `download`.
