### ISSUE TITLE
Render saved file in Rails view 

### ISSUE THREAD

**Issue by alexwebgr** [janko/down#90]
Thanks for putting this together! it really helped me with my project :) 

i am getting an error which might not be directly related to this gem but i was wondering how i can view the saved binary file in the view of my rails app

```
<%= image_tag order.store.logo %>
```
raises an error `path name contains null byte` which is probably expected :) 

i am saving it in the model like this in the logo field which is type bytea
```
    download =  Down.download(logo_url)
    self.logo = download.read
```
i can verify that the file was successfully and correctly saved in the table because Rubymine will render a preview

is there a flag or config i could set that would eliminate null bytes?
do i need to convert it to a different format?

any feedback greatly appreciated!

**Comment by jrochkind** [comment]
Hi, you don't say what frameworks/libraries you are using for your models. Probably Rails?  Whatever it is, I think this is probably a problem/question related to that framework, not to Down.  

If the `download` has a correct copy of your file, then Down has done it's job. You could check that by saving `download` to a file on disk, and opening it up in a browser or image viewing program. 

I am not sure if you are using ActiveStorage (which I am not very familiar with), or just an ordinary database column (you would want to make sure it is a binary type column instead of a text type column if you were doing this).  In general, it's not common to store binary images in a database column, it is often not considered a best practice -- but it also ought to be possible if you want to do it.  

But it's not something Down can do for you, Down just gets you the file.

**Comment by alexwebgr** [comment]
hey there

thank you for your quick response!
i am on ruby "3.2.0" and rails 7.1.3 and yes the column is binary not using acivestorage, AFAIK will still create physical files
i also agree with you that saving images in the db it is not ideal but the images are small in size and i don't anticipate a large volume of data, it also makes it easier to deploy and manage

**Comment by jrochkind** [comment]
Once you've verified that the bytes you get from Down are correct, you might try asking on a Rails forum about how to store them in the database using ActiveStorage. Perhaps over here => https://discuss.rubyonrails.org/ ?

**Comment by janko** [comment]
You probably want to render the image using a data URI:

```rb
content = order.store.logo
base64 = Base64.strict_encode64(content)
content_type = Marcel::MimeType.for(StringIO.new(content))
data_uri = "data:#{content_type};base64,#{base64}"

image_tag data_uri
```
